//Variable static types
var myString;
myString = 'hi';
console.log(myString);
var myNum;
myNum = 23;
console.log(myNum);
var myBoolean;
myBoolean = true;
console.log(myBoolean);
var myVar;
myVar = 5;
console.log(myVar);
var strArray;
strArray = ['erik', 'gardea'];
console.log(strArray);
var numArray;
numArray = [1, 2, 3];
console.log(numArray);
var boolArray;
boolArray = [true, false, true];
console.log(boolArray);
var strNumTuple;
strNumTuple = ['erik', 26];
console.log(strNumTuple);
var myVoid = undefined;
console.log(myVoid);
var myNull = null;
console.log(myNull);
var myUndefined = null;
console.log(myUndefined);
